### ISSUE TITLE
Remove explicit provider credentials' variables for reusability

### ISSUE THREAD

**Issue by viccuad** [SUSE/cap-terraform#13]
Instead of hardcoding provider credentials on a `variables.tf`,  we could either pass them as env vars, or letting terraform take the credentials from the host. This allows for easier reuse of the terraform deployments on CI.

Having the credentials included in `variables.tf` simplifies the operator life when having several similar deployments from different accounts, but I would argue that this is somewhat rare. And anyways, the same could be achieved with a file containing the env vars to be loaded, or a different wrapper like https://github.com/SUSE/catapult.

See:
https://www.terraform.io/docs/providers/aws/index.html#environment-variables
https://www.terraform.io/docs/providers/google/provider_reference.html#full-reference

**Comment by fargozhu** [comment]
@viccuad for terraform 0.12 on EKS the credentials are out from the variables files.

**Comment by fargozhu** [comment]
on EKS there are no credentials explicitly declared.
